export const siteConfig = {
  businessName: 'Plumbing Co',
  legalName: 'Plumbing Co Pty Ltd',
  siteUrl: 'https://plumbing-co.example.com',
  locale: 'en-AU',
  language: 'en',
  currency: 'AUD',
  tagline: 'Honest plumbers. Same-day if we can.',
  description:
    "Licensed plumbers serving Melbourne's inner south since 2009. Upfront pricing, no call-out fee, and we clean up before we leave.",
  founded: 2009,
  jobsCompleted: 18420,
  licenseNumber: 'VIC-PL-48217',
  address: {
    street: '12 Greville Street',
    suburb: 'Prahran',
    state: 'VIC',
    postcode: '3181',
    country: 'AU',
    formatted: '12 Greville Street, Prahran VIC 3181',
  },
  contact: {
    phoneDisplay: '(03) 9041 8200',
    phoneE164: '+61390418200',
    email: 'hello@plumbingco.com.au',
    whatsappNumber: '+61390418200',
    whatsappMessage: 'Hi Plumbing Co, I need help with a plumbing issue.',
  },
  hours: [
    { day: 'Mon–Fri', open: '07:00', close: '18:00' },
    { day: 'Saturday', open: '08:00', close: '16:00' },
    { day: 'Sunday', open: 'Emergency only', close: '' },
  ],
  serviceAreas: [
    'Prahran',
    'South Yarra',
    'Windsor',
    'St Kilda',
    'Armadale',
    'Toorak',
    'Malvern',
    'Caulfield',
    'Elwood',
    'Brighton',
  ],
  social: {
    google: 'https://g.page/plumbing-co-prahran',
    instagram: 'https://instagram.com/plumbingco',
    facebook: 'https://facebook.com/plumbingco',
  },
  review: {
    rating: 4.9,
    count: 412,
    source: 'Google',
  },
  features: {
    blog: true,
    locations: true,
    services: true,
    testimonials: true,
    contactForm: true,
    whatsapp: true,
    pricing: true,
  },
} as const;
